# Generated by Django 5.2.17 on 2026-09-12 12:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('programming', 'Programming & Scripting'), ('infosys', 'Information Systems & Design'), ('softskill', 'Soft Skills')], max_length=20)),
                ('dot_color', models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('orange', 'Orange')], default='green', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
